name: iskcon
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.8+8 #1.0.7+7 (old) (uncomment signup button and subscribe dialog button in dashboard controller) (before release check app update url for ios and android in dashboard controller)

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  get: 4.5.1
  get_storage:
  device_info_plus: ^3.2.3
  getwidget: ^2.0.5
  carousel_slider: 4.0.0
  font_awesome_flutter: ^10.1.0
  modal_bottom_sheet: ^2.0.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_screen_wake: ^1.0.2
  flutter_html: ^2.2.1
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  pull_to_refresh: ^2.0.0
  flutter_launcher_icons:
  connectivity_plus:
  image_picker: ^0.8.4+1
  # permission_handler: ^9.2.0
  razorpay_flutter: ^1.3.0
  showcaseview: ^1.1.8
  galleryimage: ^1.2.0
  flutter_local_notifications: ^9.5.1
  firebase_core: ^1.1.0
  firebase_messaging: ^11.4.2
  translator: ^0.1.7
  rating_dialog: ^2.0.4
  open_settings: ^2.0.2
  flutter_material_pickers: ^3.1.4+1
  flutter_screenutil: ^5.5.3+2
  auto_size_text: ^3.0.0
  flutter_image_compress: ^1.1.0
  cached_network_image: ^3.2.1
  url_launcher: ^6.0.0
  package_info_plus: ^1.0.0
  upgrader: ^4.6.1
  restart_app: ^1.1.0+1
  video_player: ^2.4.7
  chewie: ^1.3.6


flutter_icons:
  image_path: "assets/images/iskcon_new_logo.jpg"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/videos/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AnekTamil
      fonts:
        - asset: assets/fonts/AnekTamil-VariableFont_wdth,wght.ttf
    - family: Arima
      fonts:
        - asset: assets/fonts/Arima-VariableFont_wght.ttf
    - family: Brahmanya
      fonts:
        - asset: assets/fonts/BBT-TM-Brahmanya Tirtha_Nehru.ttf
    - family: Dayanidhi-Avvai
      fonts:
        - asset: assets/fonts/BBT-TM-Dayanidhi_Avvai.ttf
    - family: Krishna-Bold-Italic
      fonts:
        - asset: assets/fonts/BBT-TM-Krishna Bold Italic_14.8.2020.ttf
    - family: Krishna-Bold-Regular
      fonts:
        - asset: assets/fonts/BBT-TM-Krishna-Regular Bold_Ver2.ttf
    - family: Krishna-Regular
      fonts:
        - asset: assets/fonts/BBT-TM-Krishna-Regular_Ver2.ttf
    - family: Rajendra-Kurinji
      fonts:
        - asset: assets/fonts/BBT-TM-Rajendra_Kurinji.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
